### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by qwertypi** [NREL/pysam#104]
Updating my project for the end of the year, and checking when python 3.10 support might be available?

**Comment by dguittet** [comment]
We can add 3.10 support for the upcoming release this week

**Comment by sknutsonsf** [comment]
When can we expect the new release with python 3.10 support?  The current version works fine, we just need python 3.10 support.

**Comment by dguittet** [comment]
The just released PySAM v 3.0.0 has Python 3.10 support.
