### ISSUE TITLE
arm64 wheels on pypi?

### ISSUE THREAD

**Issue by dwjp** [NREL/pysam#108]
Wondering if it would be possible to get arm64 builds on pypi for the 3.0.0, suitable for running on Apple silicon? I've tried building manually from scratch, and it seems to work, but is time consuming. I can probably work around it with emulation and Docker containers, but it's a bit more tricky to maintain and there will be a performance hit.

**Comment by dwjp** [comment]
@dguittet Just noting mac amd64 wheel doesn't seem to be on pypi for the new 3.0.1 release, is there still more to be done? I don't understand if this was addressed in #112 or just one piece of the puzzle. Is there anything I can do to help?

**Comment by lazcamus** [comment]
I came here looking for arm64 linux wheels, so I'll add: when this is addressed, please build arm64 for macosx and linux

**Comment by fredrbl** [comment]
+1 on this feature! I have issues building everything from scratch, and it is really time consuming. So would be great to have pip install nrel-pysam to work on M1s.

**Comment by dylawatt** [comment]
+1 as well here. Currently we'd be using pysam but are blocked by this issue. Thanks and hope everyone on the SAM team is doing well @dguittet :)

**Comment by Zaba107** [comment]
Any updates on this issue? Thanks

**Comment by NavpreetDevpuri** [comment]
Any updates on this issue?? @dguittet

**Comment by lazcamus** [comment]
I built a linux arm64 python wheel that successfully passes the unittests... it took about a day of fighting with build stuff

**Comment by dguittet** [comment]
We are testing arm64 wheels now and are looking into how to incorporate that step into our current build process. Thanks for the patience.

**Comment by dwjp** [comment]
Thanks so much @dguittet — really appreciate all your work here!

**Comment by dguittet** [comment]
Please try out the PySAM 3.0.2 release for Python 3.8-3.10 for Apple Silicon arm64 by downloading the zip here: https://samrepo.nrelcloud.org/beta-releases/pySAM-3.0.2_arm64.zip

You can install the wheel for your python version via `pip install <path/to/downloads//dist/NREL_PySAM-3.0.2-cp39-cp39-macosx_11_0_arm64.whl`.

We will be uploading these to PyPi shortly, thanks.

**Comment by dwjp** [comment]
Hi @dguittet.

Thanks for the update here. I gave this a try, but there's one more piece missing — many users will need arm64 wheels for manylinux, per comment from @lazcamus ...

> I came here looking for arm64 linux wheels, so I'll add: when this is addressed, please build arm64 for macosx and linux

... so this will work on docker (and perhaps cloud instances using arm64 hw). Looks like there is just macosx on pypi? 

@lazcamus can you please share how you got this to build for you?

**Comment by dguittet** [comment]
@sjanzou had spent some time looking into manylinux for arm64 linux build on his machine. I don't have an arm64 computer and I am not sure if the arm64 manylinux build will work for me on my local machine. We'll discuss this and see.

**Comment by allenlawrence94** [comment]
@lazcamus - did you ever get an arm64 / manylinux wheel up and running? This has become a headache for me as well.

**Comment by lazcamus** [comment]
I have a wheel that works, but it's ubuntu 22.04 arm64 targeted. I haven't
been able to carve off time to take a pass at a manylinux arm64 wheel
build, but will get there when I can.

We use linux arm64 containers for development on macbook m1's, as it's a
_much_ easier to support environment than osx+homebrew.

**Comment by amlimaye** [comment]
I have successfully built manylinux arm64 wheels using https://github.com/NREL/pysam/blob/master/build_manylinux.sh. @dguittet, please let me know how I can help get these distributed through PyPI!

**Comment by dguittet** [comment]
Awesome @amlimaye! Could you please upload those wheel files here? Hopefully they are under the file size limit of 25 MB, otherwise could you upload some other way? We will test it out.

**Comment by dguittet** [comment]
@amlimaye Also, if you could submit any changes you made to the build scripts or build process, that would be excellent as well

**Comment by dwjp** [comment]
@amlimaye Let me know if I can help at all with testing and/or sharing here? Been running pysam inside a very slow emulated docker container all year and this will be a total life changer for me.

**Comment by amlimaye** [comment]
Apologies for the delay. No changes to the build process needed, I just followed the instructions in https://github.com/NREL/pysam/blob/master/build_manylinux.sh on a manylinux docker image from https://github.com/pypa/manylinux.

The wheels for CPython 3.6-3.10 are [here](https://drive.google.com/drive/folders/1eG1y3ESzFMKXcBrNbnmTopQIjXfuSnQA?usp=sharing). They are passing tests on my end, but please re-test on your end to confirm they work.

**Comment by dwjp** [comment]
Thanks @amlimaye  I've tested the py3.8 wheel, just manually with pvwatts so far, and seems to be working great. I think I'd need to SAM source to run the full test suite.

**Comment by dguittet** [comment]
Thanks @amlimaye for sharing the wheels! I've uploaded these to PyPi for version 3.0.2.

In the latest PySAM version, 4.0.0, just released today, there's ARM support for Mac and Linux, thanks to @sjanzou for writing the build scripts https://github.com/NREL/pysam/pull/130

**Comment by amlimaye** [comment]
Awesome, I will take down the Google drive link to the wheels soon then.
