### ISSUE TITLE
Battwatts execution error: charging loss length must be 1 or 12 for monthly input mode

### ISSUE THREAD

**Issue by jlockshin** [NREL/pysam#11]
I am trying to run a simple `Battwatts` model, where some inputs to the model are outputs from the `Pvwattsv5` model:

```python
import PySAM.Pvwattsv5 as pvwatts
import PySAM.Battwatts as battery

pv = pvwatts.default("PVWattsResidential")
pv.LocationAndResource.solar_resource_file = resource_file
pv.SystemDesign.batt_simple_enable = 1
pv.execute()

batt = battery.default("PVWattsResidential")
batt.BatteryModelSimple.batt_simple_enable = 1
batt.Common.ac = pv.Outputs.ac
batt.Common.dc = pv.Outputs.dc
batt.Common.inverter_efficiency = pv.Outputs.inverter_efficiency
batt.Common.inverter_model = pv.Outputs.inverter_model

batt.execute()
```
I receive the following error:
`error: battwatts execution error. exec fail(battery): charging loss length must be 1 or 12 for monthly input mode`

I traced the error back to line 856 of `cmod_battery.cpp` where the battery attributes `batt_loss_choice` and `batt_losses_charging` are checked. However, I cannot set the values of these variables using the `Battwatts` module from PySAM (only the `StandAloneBatteryModel`, which I've been doing as a work-around). 

Is there an issue with the way I am using `Battwatts`? I would prefer to use that simplified battery model but I am unaware of how to get rid of that error.

**Comment by dguittet** [comment]
Thanks @jlockshin for reporting this issue!

This was fixed in 1.2.dev3 and is also now in the official release version 2.0, from pull request #13
