### ISSUE TITLE
Fix charge $/day multiplied by the incorrect units

### ISSUE THREAD

**Issue by brtietz** [NREL/pysam#123]
Units reported in $/day are multiplied by 365 / 30, leading a rate of $0.16/day to be computed as $1.99/month.

However, that is much less than just multiplying the value by 30. Suggest 365/12 as a better multiplier.

**Comment by dguittet** [comment]
What pysam code is doing this?

**Comment by brtietz** [comment]
SAM doesn't support $/day units, so in the GUI an lk script handles the conversion, and resource tools handles it here.

**Comment by brtietz** [comment]
Fixed in https://github.com/NREL/pysam/pull/124

**Comment by brtietz** [comment]
It looks like due to some copy-paste errors, this isn't fixed in the URDB V8 script, and minimum charges also need to be fixed.
