### ISSUE TITLE
URDBv7_to_ElectricityRates - flatdemandmonths conversion error

### ISSUE THREAD

**Issue by relativityboy** [NREL/pysam#128]
It looks like the `flatdemandmonths` -> `ur_dc_flat_mat` converter works on accident.

The variable `flat_demand` derived from [flatdemandmonths](https://openei.org/services/doc/rest/util_rates/?version=7#:~:text=tier%3Ctier_number%3Eadj-,flatdemandmonths,-Type%3A%20array) references periods, not tiers. Unfortunately the converter swaps the concept of tiers for periods in [this line](https://github.com/NREL/pysam/blob/aeca0715367a073cc74d52572a9f28e9bd3c9f6e/files/ResourceTools.py#L263) and accumulates a series of tiers, but calls them periods on the same line.

If there it more than one tier, it then emits an incorrect error message stating that it does not support more than one period per month. `flat demand rate structure does not support multiple periods per month`

I wonder if ssc might support more than one tier per month if given a correct data-structure.

Regardless - Variable names and error messages should be corrected.

**Comment by brtietz** [comment]
Thanks for filing! We'll get this fixed in time for the next PySAM release. I was planning to test with https://apps.openei.org/USURDB/rate/view/539f6a23ec4f024411ec8beb#2__Demand, unless there's another rate you'd prefer?

**Comment by relativityboy** [comment]
That looks good. If the tests pass, I'd close it. :)
