### ISSUE TITLE
pvwattsv8 execution error

### ISSUE THREAD

**Issue by jahanbani** [NREL/pysam#133]
I am running pvwttsv8 using sub-hourly data (one year, 15-minute intervals). However, I get the following error:

`Exception: pvwattsv8 execution error.
        exec fail(pvwattsv8): Failed to process irradiation on surface (code: -105) [y:2021 m:9 d:19 h:11 minute:30].
`

I can't find the cause of this issue. My data has the following columns: `'wspd', 'df', 'dn', 'tdry', 'lat', 'lon', 'tz', 'elev', 'year', 'month', 'day', 'hour', 'minute'`

My code is working fine for other hourly data, but not for this sub-hourly data.

**Comment by dguittet** [comment]
Can you share the data? If you are not comfortable uploading it here, feel free to email it to @cpaulgilman at paulgilman@earthlink.net

**Comment by jahanbani** [comment]
[mysolardata.csv](https://github.com/NREL/pysam/files/10376376/mysolardata.csv)

Attached is the solar data.
Thank you very much, and I look forward to hearing from you.

**Comment by cpaulgilman** [comment]
These questions are being answered on the SAM forum at https://sam.nrel.gov/forum/forum-sdk/4111-pvwattsv8-execution-error-exec-fail-pvwatsv8-minute-column-required.html.
