### ISSUE TITLE
Question:  Can I use the dev branch if I need to a PV grid limit as SAM beta has?

### ISSUE THREAD

**Issue by frohro** [NREL/pysam#14]
Hi,
I need to customize the calculations SAM makes using PVWatts, Commercial, so I can have utility rates changing as a function of time.  (I'm on Guam, and they have a LEAC (fuel cost) that changes every six months, and is projected to do a healthy drop in 2022.)  I also need to limit the energy that goes back to the grid.  I found the 2018.11.11 version of SAM that goes with the released PySAM doesn't have the Grid Limits section that the 2020.1.14 beta version does.  Can and should I use the dev branch for this purpose?  Also, where should I look for examples?
Thanks,
Rob

**Comment by dguittet** [comment]
Hi @frohro, thanks for your question.

The newest PySAM 2.0.2 will have the Grid [model](https://nrel-pysam.readthedocs.io/en/master/modules/Grid.html). You can build a simulation with PVWatts, Utilityrate5 and Grid modules by chaining them together like in this example here: https://nrel-pysam.readthedocs.io/en/master/Examples.html#creating-a-simulation-from-multiple-modules

All 3 models will use the same underlying data:

```
# create pvwatts
# create grid from existing pvwatts model
# set grid curtailment ts or interconnect limit

# execution produces system generation output 'gen'
pvwatts_model.execute()

# grid curtailment applied to 'gen'
# the grid_model.Outputs.annual_energy_pre_interconnect_ac shows energy before
# grid_model.Outputs.gen shows after
grid_model.execute() 
```

**Comment by dguittet** [comment]
Closing due to lack of additional issues
