### ISSUE TITLE
Issue with my resources data

### ISSUE THREAD

**Issue by arthurdu72** [NREL/pysam#152]
**Hello everyone, 

I'm trying to make a code to simulate a wind turbine, I've linked the wind data file correctly and converted it into a dictionary so that it's in a usable format. However, the simulation doesn't work when I run it. 

Here is below the code I made :** 

import PySAM.Windpower as wp
import csv

# Create a Windpower object
wind_turbine = wp.default("WindPowerSingleOwner")

# Set the turbine parameters
wind_turbine.system_capacity = 200  # Turbine capacity in kW
wind_turbine.max_cp = 0.45  # Maximum power coefficient
wind_turbine.max_tip_speed = 80  # Maximum tip speed in m/s
wind_turbine.cut_in_speed = 3  # Cut-in wind speed in m/s
wind_turbine.cut_out_speed = 25  # Cut-out wind speed in m/s

def csv_to_dict(file_path):
    result_dict = {}
    with open(file_path, 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            val = float(row['val'])
            try:
                perc = float(row['perc'])
            except ValueError:
                perc = None
            try:
                sel_perc = float(row['sel_perc'])
            except ValueError:
                sel_perc = None
            result_dict[val] = (perc, sel_perc)
    return result_dict

# Provide the file path to your CSV file
csv_file_path = 'C:/Users/arthu/OneDrive/Documents/INTERNSHIP/SAM/05-07-2023/windSpeed.csv'

# Convert the CSV file to a dictionary
data_dict = csv_to_dict(csv_file_path)

# Print the values of data_dict
for key, value in data_dict.items():
    print(f"Key: {key}, Value: {value}")

# Construct the wind resource data dictionary
wind_resource_data = {
    'fields': ['val', 'perc', 'sel_perc'],
    'heights': [0],
    'val': [key for key in data_dict.keys()],
    'perc': [data_dict[key][0] for key in data_dict.keys() if data_dict[key][0] is not None],
    'sel_perc': [data_dict[key][1] for key in data_dict.keys() if data_dict[key][1] is not None]
}

# Print the wind resource data dictionary
print("Wind Resource Data:")
print(wind_resource_data)

# Set the wind resource data
wind_turbine.Resource.wind_resource_data = wind_resource_data

# Run the simulation
wind_turbine.execute()

# Access the wind turbine outputs
annual_energy = wind_turbine.Outputs.annual_energy

# Print the annual energy production
print("Annual Energy Production:", annual_energy, "kWh")

**When i run it, it display the following error message :** 

Exception                                 Traceback (most recent call last)
Cell In[39], line 55
     52 print(wind_resource_data)
     54 # Set the wind resource data
---> 55 wind_turbine.Resource.wind_resource_data = wind_resource_data
     57 # Run the simulation
     58 wind_turbine.execute()

Exception: Error (-4) converting nested tuple 0 into row in matrix.

I will be very glad if someone could help me

**Comment by cpaulgilman** [comment]
@arthurdu72 Please post questions about using PySAM to the SAM SDK and PySAM forum at https://sam.nrel.gov/forum/forum-sdk.html. (Perhaps you or a colleague posted [this similar question](https://sam.nrel.gov/forum/forum-sdk/4296).)

We use GitHub Issues to track and fix problems with the PySAM source code.
