### ISSUE TITLE
PySAM 3.0.2 Pvsamv1 has broken API on linux/aarch64 (python 3.10)

### ISSUE THREAD

**Issue by allenlawrence94** [NREL/pysam#153]
I have an application that uses PySAM 3.0.2. It has been working great on the x86 architecture, but I'm now trying to run it on aarch64, and I'm getting a peculiar error when running a `Pvsamv1` model:

>Exception: subarray1_rear_irradiance_loss error: Cannot load function SAM_Pvsamv1_Losses_subarray1_rear_irradiance_loss_nset. Either parameter does not exist or is not numeric type.

I've noticed that as of PySAM 4.0, `subarrayX_rear_irradiance_loss` has been dropped, so I suspect that a version of SSC later than 274 has been built into the PySAM 3.0.2 / python 3.10 / aarch64 wheel. I get this same error when I upgrade the PySAM dependency in my application to 4.2 on x86 architecture.

This error can be reproduced like so:
```python3
from PySAM import Pvsamv1


m = Pvsamv1.new()
m.Losses.assign({"subarray1_rear_irradiance_loss": 0.0})
```

I have confirmed after installing PySAM that `PySAM.__version__` is 3.0.2.

While I do hope to one day upgrade to PySAM 4 (which would presumably solve my problem), it will be quite the undertaking, so I'm hoping you might have a quicker fix, thanks!

**Comment by cpaulgilman** [comment]
Hi @allenlawrence94, from [this conversation](https://github.com/NREL/pysam/issues/108), we added support for aarch64 with PySAM 4.0.0. 

As you note, as of PySAM 4.0 the `subarray[x]_rear_irradiance_loss` input to the Pvsamv1 module [has been removed](https://nrel-pysam.readthedocs.io/en/main/version_changes/4.0.0.html#pvsamv1), so you will have to modify your code to not assign that variable to use PySAM 4.0.
