### ISSUE TITLE
Pvwattsv8 broken with major version upgrade from 3.0.2 to 4.x

### ISSUE THREAD

**Issue by joules-michael** [NREL/pysam#156]
Hello, I am finding that my Pvwattsv8 models are outputting all zeroes after upgrading the package from version 3.0.2 to any of the currently available versions 4.x.

Repro case shown in [Google Colab](https://colab.research.google.com/drive/1z3LqDR2TtB4OkMKj_MjVb3C2FWhBgd0Q?usp=sharing). I can get results comparable to those from the [online calculator](https://pvwatts.nrel.gov/pvwatts.php) with 3.0.1 and 3.0.2, but not 4.0.0 through 4.2.0.

None of the parameters referenced in the change log for Pvwattsv8 since 3.0.1 appear to be causing the issue.

**Comment by cpaulgilman** [comment]
@joules-michael I confirmed these results and am investigating. Will follow up as soon as I know more.

**Comment by brtietz** [comment]
This rhymes with https://github.com/NREL/ssc/issues/973. That said I'm having trouble identifying which inputs would have changed between versions.

**Comment by cpaulgilman** [comment]
This is caused by https://github.com/NREL/ssc/pull/830, which breaks pvwattsv8 for non-annual simulations.

A temporary workaround is to use the output `ac_pre_adjust` in place of `gen`.

**Comment by joules-michael** [comment]
Thank you for your suggestion.

I am finding that I get slightly different results across the two major versions when I compare `ac_pre_adjust`. Is this expected? 

I modified the final line of the `forecast` function in the repro case, from
```python
return np.array(system_model.Outputs.gen).reshape(-1, 1)
```
to
```python
        ac_pre_adjust = np.array(system_model.Outputs.ac_pre_adjust).reshape(-1, 1)
        gen = np.array(system_model.Outputs.gen).reshape(-1, 1) * 1000.0
        return np.concatenate((ac_pre_adjust, gen), axis=1)
```
So it looks like `ac_pre_adjust` is equivalent to `gen` (at least for my toy example), but the values of `ac_pre_adjust` differ across version 3.x vs 4.x

**Comment by cpaulgilman** [comment]
PySAM Version 4.2.0 (SSC 280) includes [this fix](https://github.com/NREL/ssc/pull/1013) to the solar position algorithm that will cause small differences in the calculated output for the Pvwattsv8 and other solar performance modules compared to older versions.

**Comment by joules-michael** [comment]
Great, thank you for clarifying!

**Comment by dguittet** [comment]
@joules-michael We fixed another issue with non-annual simulations for version 5.0.0
