### ISSUE TITLE
Problem about fetching SRW format data.

### ISSUE THREAD

**Issue by efef31016** [NREL/pysam#157]
Hello, I am ChienYao. I would like to express my appreciation for your contributions to the field of energy. I have a question regarding a package:

I am attempting to retrieve data using the **class files.ResourceTools.FetchResourceFiles**. When using **resource_type="psm3"**, I can successfully generate both .csv and .json files, and I am able to execute **files.ResourceTools.SAM_CSV_to_solar_data** without any issues. However, when I attempt to fetch wind data, I encounter difficulties at the stage of **class files.ResourceTools.FetchResourceFiles**, as it does not output valid SRW data format. I am using version 3.0.0 for this process.

This issue has been bothering me for some time, and I would greatly appreciate your valuable insights and assistance. Thank you very much for you and your team's efforts!

Best regard,
ChienYao

**Comment by cpaulgilman** [comment]
As of PySAM 4.1.0 (SSC 279), the [Windpower ](https://nrel-pysam.readthedocs.io/en/main/modules/Windpower.html#) module supports wind resource files in the CSV provided by the WIND Toolkit API, [wtk-download V2](https://developer.nrel.gov/docs/wind/wind-toolkit/wtk-download/). This is described in the [SAM release notes](https://nrel.github.io/SAM/doc/releasenotes.html) for SAM 2022.11.21 r1.

This means that the Windpower module input [`wind_resource_filename`](https://nrel-pysam.readthedocs.io/en/main/modules/Windpower.html#PySAM.Windpower.Windpower.Resource.wind_resource_filename) can be a path to either an .srw file or .csv file, and that SAM CSV Format for Wind (.csv) is the preferred format. 

In older versions, Windpower only accepted files in the SRW format, so it was necessary to convert from SAM CSV Format for WIND format to SRW.

You should be able to avoid using the SRW format in your scripts.

The ResourceTools.py also needs to be updated to reflect this change.

**Comment by efef31016** [comment]
Thank you very much for your detailed explanation. However, I have been unable to find a solution to an issue regarding an **invalid email**. Despite following the steps in the sequence, I am still unable to call the API using this email address. Thank you very much for your assistance.

<img width="800" alt="Step1" src="https://github.com/NREL/pysam/assets/60685621/9c0dc988-65a9-4db7-a35f-eb28369adc29">
<img width="914" alt="Step2" src="https://github.com/NREL/pysam/assets/60685621/2cf4e428-c199-4b97-914a-e3d3da902c8f">

**Comment by cpaulgilman** [comment]
@efef31016 I deleted the images with your email address and NREL developer key because that is private information.

Please [email me](mailto:sam.support@nrel.gov) if you are still having trouble with your calls to the NREL NSRDB API.
