### ISSUE TITLE
Issue with libssc.so on MacOS M1

### ISSUE THREAD

**Issue by warlock016** [NREL/pysam#161]
Hello,

I'm experiencing an issue on my macOS M1 computer when trying to run a Python script that utilizes both `pvlib` and `nrel-pysam` libraries. The problem arises specifically when I attempt to use functionalities from `nrel-pysam`.

**Environment:**
- OS: macOS (Apple M1)
- Python Version: 3.11
- `pvlib` Version: 0.9.4
- `nrel-pysam` Version: 5.0.0
- Installation method: conda 

**Issue Description:**
Upon executing my script, I encounter the following OSError related to loading the `libssc.so` library:

OSError: dlopen(/Users/mode/anaconda3/envs/pvsim/lib/python3.11/site-packages/PySAM/libssc.so, 0x0006): tried: '/Users/mode/anaconda3/envs/pvsim/lib/python3.11/site-packages/PySAM/libssc.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/mode/anaconda3/envs/pvsim/lib/python3.11/site-packages/PySAM/libssc.so' (no such file), '/Users/mode/anaconda3/envs/pvsim/lib/python3.11/site-packages/PySAM/libssc.so' (not a mach-o file)

This error prevents me from utilizing the `nrel-pysam` library for my pv energy simulation project. I suspect this might be related to compatibility issues with the M1 chip or with the Python version.

**Steps to Reproduce:**
1. Set up a new conda environment with Python 3.11.
2. Install `pvlib` and `nrel-pysam` using condas respective channels.
3. Attempt to run a script that calls `nrel-pysam` functionalities.

**Attempted Solutions:**
- I have tried reinstalling both `pvlib` and `nrel-pysam`.
- I have also attempted creating a new environment with a different Python version.
- I have checked for any known issues on the GitHub repositories and forums but haven't found a solution.

I would greatly appreciate any advice, workarounds, or information on upcoming fixes that might resolve this compatibility issue. Thank you in advance for your assistance.

Best regards,
Mode

**Comment by warlock016** [comment]
With nrel-pysam 4.2 everything works correctly.

**Comment by dguittet** [comment]
Sorry about that. We are releasing a new patch soon with a new version of PySAM that should fix this

**Comment by dguittet** [comment]
Should be fixed with the latest release 5.1.0
