### ISSUE TITLE
pysam local github install failing 

### ISSUE THREAD

**Issue by shirubana** [NREL/pysam#168]
Yellow :)

I might be  doing something wrong, but i'm getting this issue when I try to reinstall pysam to bring it hopefully to a newer version from my github folder... thoughts? 
![image](https://github.com/NREL/pysam/assets/22824806/23a123ee-67d6-408b-b122-171411506c9f)

**Comment by brtietz** [comment]
Hello! setup.py requires a built version of SAM to pull the underlying ssc models. Instructions for setting up all of SAM are at https://github.com/NREL/SAM/wiki.

Is there a particular feature or branch you're looking for? PySAM 5.1.0 is only missing ~two months of development.

**Comment by shirubana** [comment]
Ah! Thanks. Na, I'll just install pysam through pip then :)
