### ISSUE TITLE
Python 3.11.7 bug on Json read? 

### ISSUE THREAD

**Issue by shirubana** [NREL/pysam#172]
![image](https://github.com/NREL/pysam/assets/22824806/f188d46e-8d72-4a17-875c-a1f8f11e1c82)

Having trouble opening a Sam-exported SamJson file on the new python.
This works well on Python 3.11.4
It doesn't work on Python 3.11.7 , so suspecting this is the issue.

Info about our system (the one that runs; other one is the same but 3.11.7)
![image](https://github.com/NREL/pysam/assets/22824806/2473b5a0-bd55-487d-b9e9-068bed6da146)

This is the journal, SAM file and Jsons we were using to test in both computers
https://github.com/shirubana/pySAMtutorial/tree/main/4%20-%20Passing%20POA%20through%20pySAM

**Comment by dguittet** [comment]
It looks like it's due to this issue: https://github.com/NREL/pysam/issues/164

This issue is fixed but hasn't been released yet.

**Comment by shirubana** [comment]
Thanks Darice!

This is what I'm getting trying that solution on python 3.11.7, but maybe I'm interpreting it wrong ? @dguittet 
![image](https://github.com/NREL/pysam/assets/22824806/e09bc19f-6de5-4fd1-9529-b60fdf91bf62)

(btw, it seems it indees was/is related to the python version, the computer that had 3.11.7 we added an environment with 3.11.4 and it worked).

**Comment by dguittet** [comment]
Can you print the `k` values that are causing issues?

**Comment by shirubana** [comment]
![image](https://github.com/NREL/pysam/assets/22824806/c8caee51-2b34-444e-98f0-97003573d8ea)

**Comment by dguittet** [comment]
Ah, try switching the code to

```
if 'adjust_` in k:
```

**Comment by shirubana** [comment]
sweet, that seem to have worked! thank you for helping us troubleshoot, and sorre we didn't identified that issue as related.

![image](https://github.com/NREL/pysam/assets/22824806/429bd4af-2ef4-4a26-9a06-2d06db678b7c)
