### ISSUE TITLE
Notations for variables that need recomputing missing....

### ISSUE THREAD

**Issue by frohro** [NREL/pysam#22]
On [this page](https://nrel-pysam.readthedocs.io/en/master/Import.html) the documentation states, "In each PySAM Module’s page, each variable that may be affected by such equations will have a “Changes to this variable may require updating the values of the following” and “This variable may need to be updated if the values of the following have changed” section to provide suggestions for which variables may be affected upstream or downstream."  I am finding any notations like that on the [Cashloan page](https://nrel-pysam.readthedocs.io/en/master/modules/Cashloan.html), but when I change the size of the solar array (Pvwatts7.SystemDesign.system_capacity), the net capital cost  (Cashloan.Outputs.adjusted_installed_cost) doesn't change.  
I searched for warning notes about this in Pvwatts7, and Utilityrate5, and don't think I found any warnings there, so I thought I was home free.  :-)  It doesn't look that way at the moment.
I'm enclosing my python code, and the files I'm using to check things.  
[Recompute_problem.zip](https://github.com/NREL/pysam/files/4240711/Recompute_problem.zip)
For me, it really doesn't matter what installed cost was used.  I just need to know what was used for the calculation, because I need to subtract it out, except for the actual first year, which is correct.  :-) 
I would like to know if I'm looking in the wrong place for the documentation, etc.
Am I missing something?  I must be.
Thanks so much for all your help!
Rob

**Comment by dguittet** [comment]
Thanks for bringing this up! Indeed you're correct that some documentation is missing (surprise! :P) The available list only describes dependencies between variables in the same model.

What you're noticing is a dependency between variables in different models (`system_capacity` in pvwatts and `total_installed_cost` in cashloan). There are many of equations, and unfortunately, they haven't been available to SDK users. I've migrated a few of these but there are many... 

total_installed_cost` is calculated in the SAM GUI as `total_direct_cost` + `total_indirect_cost` where total_direct_cost is calculated [here as:](https://github.com/NREL/SAM/blob/4e8b03ab8294f7d71072fef6fb9b0e1ed875fd41/deploy/runtime/ui/PV%20Capital%20Costs.txt#L6254)

```
equations{ 'total_direct_cost' } = define() {
	return ${module_total}
		+${inverter_total}
		+${bos_equip_total}
		+${install_labor_total}
		+${install_margin_total}
		+${contingency}; };
```

where `module_total` and `inverter_total` is dependent on `system_capacity`, dc ac ratio, etc.

Likewise total_indirect_cost is 

```
equations{ 'total_indirect_cost' } = define() {
	return ${permitting_total}
		+${engr_total}
		+${grid_total}
		+${land_total}
		+${landprep_total}
		+${sales_tax_total}; };
```

All of these variables are defined in SAM GUI but not in PySAM. So the link between system_capacity to costs is missing.

If you don't care about costs, you can just change `total_installed_cost` along with other costs in https://nrel-pysam.readthedocs.io/en/2.0.2/modules/Cashloan.html such as those in the SystemCosts group.

**Comment by frohro** [comment]
Thanks Darice,
Would it be more accurate or better to tell users that the blue variables in SAM are computed by the GUI, and at this point PySAM does not do that?  So if you change a black variable, you need to adjust all the blue ones that depend on that black one.  
I found it a tad amusing that you look at the code to determine what depends on what.  You are definitely a much better coder than I ever hope to be.  So far, I use common sense about how these variables are related to guess the relationship, and then test my suppositions, by comparing results with SAM.  :-)  It would be handy to have a list of what depends on what, and their relationships.  I may be able to do this for the pvwatts commercial simulation I'm using, but doing it for the whole SDK is only slightly less daunting than making PySAM update all the values like the GUI does, though it might be a step along the way.  :-)
Thanks again!
Rob

**Comment by frohro** [comment]
Never mind.  I found [this](https://www.w3schools.com/python/python_tuples.asp).

**Comment by dguittet** [comment]
The list of dependencies between different models would be really long. I think it makes more sense to keep moving the dependencies out of the GUI, which we are doing incrementally.

If you happen to reproduce any of those dependencies in your python code, that would be something we'd definitely want to add to pysam.

**Comment by dguittet** [comment]
The list of dependencies between different models would be really long. I think it makes more sense to keep moving the dependencies out of the GUI, which we are doing incrementally.

If you happen to reproduce any of those dependencies in your python code, that would be something we'd definitely want to add to pysam.
