### ISSUE TITLE
How can I assign Utilityrate5.ElectricityRates.ur_ec_tou_mat, as it is a tuple?

### ISSUE THREAD

**Issue by frohro** [NREL/pysam#23]
Hi Darice,
This is probably just a python thing, and I'm not really very versed in python, but I need to assign different rates to my different simulations to make a varying rate simulation, and unfortunately, I don't know how to change the value of a tuple.

type(ur.ElectricityRates.ur_ec_tou_mat)
Out[114]: tuple

Paul tried to help me [here](https://sam.nrel.gov/forum/forum-sdk/2928-utilityrate5-electricityrates-ur-ec-tou-mat-a-touple-does-not-support-item-assi.html#7997), but I'm still stuck.  
Thanks,
Rob

**Comment by dguittet** [comment]
I think you meant to close this issue https://github.com/NREL/pysam/issues/22#issuecomment-590664269

**Comment by cwhanse** [comment]
> Hi Darice,
> This is probably just a python thing, and I'm not really very versed in python, but I need to assign different rates to my different simulations to make a varying rate simulation, and unfortunately, I don't know how to change the value of a tuple.
> type(ur.ElectricityRates.ur_ec_tou_mat)
> Out[114]: tuple
> Paul tried to help me here, but I'm still stuck.
> Thanks,
> Rob

Sorry to necro a closed issue, but just in case you didn't get an answer: its a python thing. You can't change an element of a tuple.

But you can translate the tuple to a list, change the element, and then convert the list to a tuple, and then assign the new tuple to ur.ElectricityRates….

Example:
```
tup = tuple(2, 3, 4)  # = ur.ElectricityRates.ur_ec_tou_mat
tup_as_list = list(tup)
tup_as_list[2] = 5
new_tup = tuple(tup_as_list)
# ur.ElectricityRates.ur_ec_tou_mat = new_tup
```
Hope that helps.
