### ISSUE TITLE
Net Present Value in SAM and PySAM Don't Agree

### ISSUE THREAD

**Issue by frohro** [NREL/pysam#24]
This is in the 2020.1.17 beta and the 2020.2.24 beta.  I mentioned this in a previous issue, but at that time I thought the problem was that PVWatts wasn't giving me the correct data, and that caused the NPV to be off, but PVWatts was not the problem.  I thought I better open a new issue, because that one still has unanswered questions, but this one is really somewhat separate.  

I tried this with the default project, and SAM and PySAM agree.  
Steps to reproduce:

- Unzip the files enclosed.
- Load the enclosed SAM file.
- Run the simulation for the simulation titled NPV Not Right.
- Note the NPV is $196,043.
- Generate code -> JSON for inputs
- Put it in the directory with the enclosed python script.
- Run the python script.
- Note the cl.Outputs.npv is $200,340.

I hope this is useful.  The difference isn't enough to cause me great grief, but something seems amiss.  If you see anything wrong with my python script, please let me know.  I'm using it as an example for the docs.
Thanks,
Rob
[NPV_Not_Right.zip](https://github.com/NREL/pysam/files/4279115/NPV_Not_Right.zip)

**Comment by dguittet** [comment]
The SAM file's missing from the zip unfortunately.

**Comment by dguittet** [comment]
Without your specific case, I ran your script on the default PVWatts Commercial configuration and found it to match:

![image](https://user-images.githubusercontent.com/29387736/76787162-168b7580-677e-11ea-8779-b6375dff6ba6.png)

**Comment by frohro** [comment]
Hi Darice,
It has been too long since I submitted this.  I don't know what the exact problem might have been.  I was able to duplicate the output above for this, but if you look the npv there does indeed agree with the NPV from SAM.  It has been too long, and now I suspect I was doing something wrong, so let's close this one!  I think it is okay now!
Rob

**Comment by frohro** [comment]
Okay, I found the example that doesn't work again.  Here it is in this zip.  All you need is the .sam file and the python.
Thanks,
Rob
[NPV_not_the_same.zip](https://github.com/NREL/pysam/files/4341564/NPV_not_the_same.zip)

**Comment by dguittet** [comment]
Thanks frohro! The issue was that the "grid" compute module wasn't added to the PySAM sequence of simulations since I had forgotten to add that in the Examples and Documentation. I'll amend those docs now. Thanks for your detailed effort! Here's the fixed code:

```
pv_dat = pssc.dict_to_ssc_table(dic, "pvwattsv7")
grid_dat = pssc.dict_to_ssc_table(dic, "grid")
ur_dat = pssc.dict_to_ssc_table(dic, "utilityrate5")
cl_dat = pssc.dict_to_ssc_table(dic, "cashloan")
pv = PVWatts.wrap(pv_dat)
grid = Grid.from_existing(pv)
ur = UtilityRate.from_existing(pv)
cl = Cashloan.from_existing(pv)
grid.assign(Grid.wrap(grid_dat).export())
ur.assign(UtilityRate.wrap(ur_dat).export())
cl.assign(Cashloan.wrap(cl_dat).export())

# The models are executed in order.  Note that the outputs from the first 
# simulation are automatically available for the next one, and so on.  :-)
pv.execute()
grid.execute()
ur.execute()
cl.execute()
```
