### ISSUE TITLE
broken links on pypi page

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/pysam#28]
The PyPI page (https://pypi.org/project/NREL-PySAM/) has the documentation link as https://pysam-docs.readthedocs.io/en/latest/ in two places:  once under "Project Description" and once in the sidebar as the project home page.  Also, the changelog on that page appears out of date.

**Comment by dguittet** [comment]
Thanks for pointing that out! I've changed those links on this repo, but they won't take effect on PyPi until I upload a new package.
