### ISSUE TITLE
'system_use_lifetime_output' not working with Pvwattsv7

### ISSUE THREAD

**Issue by skoeb** [NREL/pysam#31]
I'm trying to get a multi-year generation profile from Pvwattsv7, I believe I should be using the `system_use_lifetime_output` argument to specify this, and than accessing `generator.Outputs.dc`, however the length of the output array is still only 8760. 

```
import PySAM.Pvwattsv7 as pv

# --- Initialize Generator ---
generator = pv.default('PVWattsMerchantPlant')

# --- Load Resource File from FetchResourceFile ---
generator.SolarResource.solar_resource_file = 'data/PySAM Downloaded Weather Files/-83.572_41.475_psm3_60_tmy.csv'

# --- Assign 20 year lifetime ---
generator.Lifetime.assign({'system_use_lifetime_output':1,
                           'analysis_period':3,
                           'dc_degradation':[0.005]*3})

# --- Execute ---
generator.execute()

print(len(generator.Outputs.dc))
```

```
output> 8760
```

Am I missing an argument? Version 2.0.2 install with pip.

Thanks!

**Comment by skoeb** [comment]
This appears to only be an issue with the PVWattsV7 module, not Pvsamv1

**Comment by brtietz** [comment]
Sam,

pvwatts and pvsamv1 handle lifetime analysis differently. pvsamv1 runs the simulation for every year with the detailed degradation models, producing dc power outputs for all years in the analysis period. pvwatts takes the output from the first year, and scales it by the ac degradation rate for the financial models. Therefore 8760 is the expected length of the dc output array in pvwatts, regardless of analysis period.

I'll update the docs so this is more clear, and let us know if you have more questions.

Brian

**Comment by skoeb** [comment]
Thanks Brian! That difference makes sense, out of curiosity, is there a way to run a Merchant Plant PVWatts with a multi-year hourly wholesale forecast? This seems to be possible in the GUI. 

Ideally, I think it would be great if a switch existed (in both PySAM and the GUI) to just use the lifetime output for the MerchantPlant "cleared capacity", i.e. assuming that all generation clears.

-Sam

**Comment by dguittet** [comment]
As Brian said, since PVWatts doesn't run the lifetime "realistically" we've historically discouraged use of PVWatts for lifetime simulations, which is why the full lifetime vector has been a "hidden" output-- and therefore doesn't show up in PySAM. Only recently, with changing lifetime simulations to be the default for several configurations, including all with batteries and the Merchant Plant, have we added lifetime PVWatts into the GUI.

I'll expose the lifetime output vector (called "gen") in PySAM's PVWatts and upload a new version with that fix today or tomorrow.

@janinefreeman who may have more insight into the decision regarding the switch for all generation clearing.

**Comment by janinefreeman** [comment]
Although pvwattsv7 has lifetime mode, it is only used in the fuel cell model- the PVWatts GUI still actually doesn't have "lifetime mode" as an option. However, it should be working in lifetime mode in the SDK/PySAM- the code I see has "gen" already as a lifetime output from pvwattsv7 (line 346 in pvwattsv7) ? I think the problem may be the output you're looking for @skoeb - only the AC side generation is available as a lifetime array. DC generation is only available for the first year in PVWattsV7.

**Comment by skoeb** [comment]
Thanks Darice and Janine. I think the 'gen' output is what I was looking for. I've also just switched over to using Pvsam1, as the inputs are more robust. Feel free to close this!

**Comment by dguittet** [comment]
Okay, sounds good! 

`gen` output for PVwatts which is the AC side lifetime generation added in NREL/ssc#372
