### ISSUE TITLE
Cannot assign Solar Resource using tools.TMY_CSV_to_solar_data()

### ISSUE THREAD

**Issue by kurt-rhee** [NREL/pysam#34]
`def get_resource(latitude, longitude):
    # --- Initialize Sun Fetcher ---
    sunfetcher = tools.FetchResourceFiles(
                    tech='pv',
                    workers=1, #thread workers if fetching multiple files
                    nrel_api_key='3LFmI97FanZVzvNlN0LiL0dRNU3y3Mxj5rGfinca',
                    nrel_api_email='kurt.rhee@edf-re.com')
    
    # --- Pass a list of (lon, lat) tuples or Shapely points to fetch the nearest resource data ---
    lon_lats = [(longitude, latitude)]  # golden CO
    sunfetcher.fetch(lon_lats)
        
    # --- Get resource data file path ---
    path_dict = sunfetcher.resource_file_paths_dict
    fp = path_dict[lon_lats[0]]
    
    solarResource = tools.TMY_CSV_to_solar_data(fp)
    
    return solarResource`

I get an unnamed exception when using the solarResource dictionary returned by this function when assigning this dictionary to system_model.

system_model.SolarResource.assign(solarResource)

Thank you for your assistance.

**Comment by dguittet** [comment]
`TMY_CSV_to_solar_data` returns a dictionary that should be assigned to `system_model.SolarResource.solar_resource_data`.

The following code here is an example:

```
import PySAM.ResourceTools as tools
import PySAM.Pvwattsv7 as pv

# --- Initialize Wind Fetcher ---
sunfetcher = tools.FetchResourceFiles(
                    tech='pv',
                    workers=1, #thread workers if fetching multiple files
                    nrel_api_key='3LFmI97FanZVzvNlN0LiL0dRNU3y3Mxj5rGfinca',
                    nrel_api_email='kurt.rhee@edf-re.com')

# --- Pass a list of (lon, lat) tuples or Shapely points to fetch the nearest resource data ---
lon_lats = [(-105.1800775, 39.7383155)]  # golden CO
sunfetcher.fetch(lon_lats)

path_dict = sunfetcher.resource_file_paths_dict
fp = path_dict[lon_lats[0]]

solarResource = tools.TMY_CSV_to_solar_data(fp)

m = pv.default("Pvwattsnone")
m.SolarResource.solar_resource_data = solarResource
m.execute()
print(m.Outputs.annual_energy)
```

**Comment by kurt-rhee** [comment]
Understood, thank you very much for your help.
