### ISSUE TITLE
Documentation Question on Soiling

### ISSUE THREAD

**Issue by kurt-rhee** [NREL/pysam#35]
![image](https://user-images.githubusercontent.com/33131958/83556690-36048580-a4c5-11ea-9a58-145064f1f630.png)

Hello what is the timestep of this soiling sequence, is it monthly?

**Comment by cpaulgilman** [comment]
Yes, the soiling loss input is an array of 12 percentage values, one for each month of the year. During a simulation, the beam irradiance for each time step in a month is multiplied by the soiling loss for that month.

**Comment by kurt-rhee** [comment]
Thank you for the information!

**Comment by kurt-rhee** [comment]
I have another theoretical question, how does PVwatts v7 calculate bifacial gain if I don't specify albedo in model.SolarResource?

I see that changing bifaciality changes my energy value.

Thanks,

Kurt

**Comment by kurt-rhee** [comment]
Very helpful, thank you Paul
