### ISSUE TITLE
FetchResourceFileExample.py not working

### ISSUE THREAD

**Issue by MarcoGiacomo** [NREL/pysam#45]
Maybe I'm doing something incorrect. I'm trying to use the code FetchResourceFileExample.py to download wind data but I always encounter the some issues. 

Initially I have the following error when running (wtkfetcher.fetch(lon_lats)):
Beginning data download for wind using 1 thread workers
Downloading wind toolkit file for 39.7383155_-105.1800775...
C:\Users\JonnSmithi\anaconda3\lib\site-packages\urllib3\connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'developer.nrel.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

Then moving on when I run the code I get the following error: windpower execution error. exec fail(windpower): failed to read local weather file: error at year_response could not open file for reading: error at year_response

At the line 35 when I'm using:  wtk_path_dict = wtkfetcher.resource_file_paths_dict, I obtain a dictionary in Python with the key equals to the lon and lat and as a value a string = 'error at year_response' (I have changed location and years[2007 to 2013] but always the same error occurs)

What I'm doing wrong? can you please help me with this?

Thank you very much in advance

**Comment by dguittet** [comment]
Hi @MarcoGiacomo, I have replicated that issue on our test and Example. I heard yesterday that the issue currently is from the Wind Tool Kit side. @cpaulgilman may have more details on a resolution timeline.

**Comment by cpaulgilman** [comment]
The WIND Toolkit API has always had some issues, but some updates made in the last couple of weeks (July 2020) should have fixed them. I tested a wind file download from the desktop version of SAM today and it worked.

It might be useful to modify the _windtk_worker() and other similar functions in [ResourceTools.py](https://github.com/NREL/pysam/blob/master/files/ResourceTools.py) to print or in some other way report the URL it sends to the web API for test purposes. Then you could manually test the URL in a browser to see the API's response and confirm that it is an issue with the API and not something in the Python code.

**Comment by dguittet** [comment]
Thanks Paul! I've tried your suggestion of pasting the URL into the browser and indeed was able to download. It looks like the problem is that the formatting has changed!

Updating that now.

**Comment by MarcoGiacomo** [comment]
@dguittet and @cpaulgilman thank you very much for your help! Now it works, it downloads the data and execute the model, even if it is still providing me the error when using the line code: 

wtkfetcher.fetch(lon_lats)

InsecureRequestWarning: Unverified HTTPS request is being made to host 'developer.nrel.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
