### ISSUE TITLE
Stub file syntax error

### ISSUE THREAD

**Issue by dguittet** [NREL/pysam#47]
As reported here: https://sam.nrel.gov/forum/forum-open-source/3057, there are missing colons in the stub files resulting in `mypy` errors.

**Comment by larsrinn** [comment]
Is there an ETA when this will be released to PyPI? With the syntax errors in the stubs, mypy fails even though I added:

```
[mypy-PySAM]
ignore_errors = true
```

to `mypy.ini`.

**Comment by dguittet** [comment]
Just out today with PySAM v2.2.0. Available on PyPi, upcoming on Anaconda.

**Comment by larsrinn** [comment]
Cool, thank you

**Comment by steffen746** [comment]
I still have syntax errors in the stub files.
In stubs/stubs/Irradproc.pyi the global key word causes a mypy error


```
class IrradianceProcessor(object):
	def assign(self): 
		pass
```

	def export(self) -> Dict[Dict]:
		pass

	def __init__(self, *args, **kwargs): 
		pass


	albedo = tuple
	albedo_const = float
	azimuth = float
	backtrack = float
	beam = tuple
	day = tuple
	diffuse = tuple
	elevation = float
	gcr = float
	global = tuple
	hour = tuple
