### ISSUE TITLE
InverterMermoudLejeuneModel Input Parameter Values

### ISSUE THREAD

**Issue by lukereed** [NREL/pysam#5]
Is there a working example of an input dictionary that could be used via the `PySAM.Pvsamv1.Pvsamv1.InverterMermoudLejeuneModel.assign()` method? I am presently parsing in values from supplier OND files and have included an example `.export()` from the inverter object.

When I attempt to run with the following inverter object, the model falls over and all I have as an error message is: "Process finished with exit code 3". I have had an issue with this using a modified SAM sscapi.py file as well with the `self.data_set_matrix` method. When running directly from the SAM SDK sscapi.py, it falls over with a windows error.

Below is my current inverter object. Is this a known issue, or do I have a problem with my input format? I have no issues when replacing the MLM inverter module with the datasheet inverter module.

```
{
  "ond_Aux_Loss": 0.0,
  "ond_CompPMax": "Lim",
  "ond_CompVMax": "Lim",
  "ond_IMaxAC": 2150.0,
  "ond_IMaxDC": 0.0,
  "ond_INomAC": 2150.0,
  "ond_INomDC": 0.0,
  "ond_ModeAffEnum": "Efficiencyf_POut",
  "ond_ModeOper": "MPPT",
  "ond_NbInputs": 24.0,
  "ond_NbMPPT": 1.0,
  "ond_Night_Loss": 200.0,
  "ond_PLim1": 1995000.0,
  "ond_PLimAbs": 0.0,
  "ond_PMaxDC": 0.0,
  "ond_PMaxOUT": 2310000.0,
  "ond_PNomConv": 2100000.0,
  "ond_PNomDC": 0.0,
  "ond_PSeuil": 2887.5,
  "ond_TPLim1": 55.0,
  "ond_TPLimAbs": 60.0,
  "ond_TPMax": 25.0,
  "ond_TPNom": 50.0,
  "ond_VAbsMax": 1500.0,
  "ond_VMPPMax": 1310.0,
  "ond_VMppMin": 891.0,
  "ond_VNomEff": [
    891.0,
    970.0,
    1200.0
  ],
  "ond_VOutConv": 630.0,
  "ond_doAllowOverpower": 1.0,
  "ond_doUseTemperatureLimit": 1.0,
  "ond_effCurve_Pac": [
    [
      0.0,
      222600.0,
      445200.0,
      667800.0,
      1113000.0,
      1669500.0,
      2226000.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      222600.0,
      445200.0,
      667800.0,
      1113000.0,
      1669500.0,
      2226000.0,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      222600.0,
      445200.0,
      667800.0,
      1113000.0,
      1669500.0,
      2226000.0,
      0.0,
      0.0,
      0.0
    ]
  ],
  "ond_effCurve_Pdc": [
    [
      2887.5,
      228636.0,
      453776.4,
      678589.5,
      1128231.1,
      1692689.9,
      2259439.8,
      0.0,
      0.0,
      0.0
    ],
    [
      2887.5,
      228706.5,
      453915.2,
      677969.5,
      1129032.2,
      1694407.8,
      2259210.4,
      0.0,
      0.0,
      0.0
    ],
    [
      2887.5,
      228542.1,
      454146.7,
      678382.7,
      1130178.7,
      1695268.0,
      2261505.6,
      0.0,
      0.0,
      0.0
    ]
  ],
  "ond_effCurve_elements": 3.0,
  "ond_effCurve_eta": [
    [
      0.0,
      0.9735999580118616,
      0.981099942614909,
      0.9841001076497647,
      0.986500017593913,
      0.9862999714241811,
      0.9851999597422335,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.9732998406254304,
      0.9807999379619805,
      0.9850000626871858,
      0.9858000506982884,
      0.9852999968484564,
      0.9852999968484565,
      0.0,
      0.0,
      0.0
    ],
    [
      0.0,
      0.9739999763719682,
      0.980299977958664,
      0.984400103363485,
      0.984800014369409,
      0.9848000434149645,
      0.9843000167675905,
      0.0,
      0.0,
      0.0
    ]
  ],
  "ond_lossRAc": 0.0,
  "ond_lossRDc": 0.0
}
```

**Comment by janinefreeman** [comment]
Hi @lukereed ! Thanks for posting. Unfortunately, we don't have a lot of examples for the implementation of the Mermoud Lejeune Inverter model, as that was a third party contribution. There is an example in C++ in our google tests that you could check against your values, in the file [https://github.com/NREL/ssc/blob/develop/test/input_cases/pvyield_common_data.h] starting around line 387. @timorichert might also be able to provide some insight as to whether your inputs look right or not.

**Comment by lukereed** [comment]
Hi @janinefreeman ! Thanks for the follow-up. I'll if I can get a working MLM case from the C++ example, and if/when I do I will be sure to share with the community. Thanks!!

**Comment by lukereed** [comment]
@timorichert are you able to offer any insight to this? I attempted to reproduce the configuration outlined in the [example test case](https://github.com/NREL/ssc/blob/develop/test/input_cases/pvyield_common_data.h) but still ran into the same issue. It appears to be an underlying problem as all data structures are accepted into the inverter model.
Additionally, is there any documentation of the PV_Yield methodology that was applied for the inverter model and/or supporting scientific papers?
