### ISSUE TITLE
BatteryTools.size_li_ion_battery(): Is`batt_power_discharge_max_kwac` really AC? 

### ISSUE THREAD

**Issue by spolloni** [NREL/pysam#55]
Hi there,

I am wondering if the setting of `batt_power_charge_max_kwac` (and `batt_power_discharge_max_kwac`) in the `size_li_ion_battery()` function of `BatteryTools` is truly expressed in AC.  Let's consider the case where the model's `batt_ac_or_dc` key in `BatterySystem` is set to `1.0`, and therefore the `ac_connected` ([this line](https://github.com/NREL/pysam/blob/f7db99c50f5cef122ff493ecdc0cc25893a4b764/files/BatteryTools.py#L86)) and `size_by_ac_not_dc` ([this line](https://github.com/NREL/pysam/blob/f7db99c50f5cef122ff493ecdc0cc25893a4b764/files/BatteryTools.py#L87)) booleans are both `True`. The `desired_power` variable is mutated [here](https://github.com/NREL/pysam/blob/f7db99c50f5cef122ff493ecdc0cc25893a4b764/files/BatteryTools.py#L97)  and converted to DC. It then seems that `desired_power` is still in DC when assigned to `batt_power_charge_max_kwac`, see [this line](https://github.com/NREL/pysam/blob/f7db99c50f5cef122ff493ecdc0cc25893a4b764/files/BatteryTools.py#L142) and [this line](https://github.com/NREL/pysam/blob/f7db99c50f5cef122ff493ecdc0cc25893a4b764/files/BatteryTools.py#L154). Is this a bug, or am I misunderstanding the code?

thanks for looking into it!

**Comment by dguittet** [comment]
Thanks @spolloni for reporting the bug! Indeed the sizing behavior is off.
