### ISSUE TITLE
Version 2.2.0 not yet uploaded to conda

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/pysam#68]
2.2.0 is up on pypi: https://pypi.org/project/NREL-PySAM/#files
but the latest version on conda is 2.1.4: https://anaconda.org/NREL/nrel-pysam/files?sort=time&sort_order=desc and `conda search -c nrel nrel-pysam`

Bonus points if a py3.9 build is made available on conda too :)

**Comment by dguittet** [comment]
Working on this 👍 https://github.com/NREL/pysam/commit/98a02b7207d2b48f534d25def837b3b232a5cafd

**Comment by dguittet** [comment]
I've uploaded Version 2.2.0 to conda for 
 - Linux for Python 3.6-3.9
 - Mac, 3.6 - 3.9

Windows will take some more time as I wait for network issues to be resolved for my remote VM

**Comment by dguittet** [comment]
Uploaded for Windows, Python version 3.6-3.9
