### ISSUE TITLE
Example code for Resource Tools URDBv7_to_ElectricityRates throws error

### ISSUE THREAD

**Issue by brtietz** [NREL/pysam#72]
Attempting to use the example code from https://nrel-pysam.readthedocs.io/en/master/Tools.html?highlight=utility%20rate#resource-tools for ResourceTools.URDBv7_to_ElectricityRates throws the error "Must assign Technology module attributes with nested dictionaries" Iterating through the key-value pairs and using Utilityrate5.value works.

Either update ResourceTools.URDBv7_to_ElectricityRates to return the correct dictionary format for assign or update the example to iterate over key-value pairs.

**Comment by dguittet** [comment]
I added some additional error reporting to show which Group is causing the issue -- see #74 

What is the URDB data you're using that is throwing this error?

**Comment by brtietz** [comment]
This was the rate in question: https://openei.org/apps/IURDB/rate/view/5d711dd65457a3fe2e466f69

I tried to test it just now with the latest on branch pysam-v2.2.1, but ran into the following issue:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-6-a4e11dbbfac2> in <module>
     18 # Update utility rate to match SDGE
     19 urdb_response_json = json.loads(urdb_response)["items"][0]
---> 20 rates = PySAM.ResourceTools.URDBv7_to_ElectricityRates(urdb_response_json)
     21 ur.assign(rates)
     22 

~\Anaconda3\envs\pysam_master\lib\site-packages\nrel_pysam-2.2.1-py3.8-win-amd64.egg\PySAM\ResourceTools.py in URDBv7_to_ElectricityRates(urdb_response)
    237         urdb_data['ur_dc_flat_mat'] = flat_mat
    238 
--> 239     if urdb_data['ur_dc_enable'] == 1 and "ur_dc_tou_mat" not in urdb_data.keys():
    240         urdb_data['ur_dc_tou_mat'] = [[1, 1, 1e38, 0], ]
    241         urdb_data['ur_dc_sched_weekday'] = [[1] * 24 for i in range(12)]

KeyError: 'ur_dc_enable'
```

Looks like there might need to be a try-except in the code from https://github.com/NREL/pysam/commit/9cd1faad618b070d11822627398e976f9f78d0a5 for energy only rates.

It is extremely likely that I was calling model.assign, is there a way to make that error message more descriptive?

**Comment by brtietz** [comment]
I went ahead with the "set ur_dc_enable to 0" approach and pushed it to pysam-v2.2.1: https://github.com/NREL/pysam/commit/6896b4efe5d6ba4dd9e00be06fd80aa0946147f0

Calling model.assign was, in fact, the problem. Should I try to update the error message to the above comment, or should we close this issue?

**Comment by dguittet** [comment]
I think setting a default makes sense. However, `ur_dc_enable` is a SSC variable, not a return variable from the URDB, so the if you added will always be false. `ur_dc_enable` should be True if there is flat or tou demand info from the URDB. However, once ur_dc_enable is true, then sam requires both the flat and the tou info even if only one of them is provided.

I think the error message is more general as it stands as you can run into the same error for another reason... perhaps you could try updating it to state that the type was expected to be a dictionary but was found to be invalid? Hopefully that's descriptive enough.

**Comment by brtietz** [comment]
Ah, right - I've updated it to check for the other type of demand charge: https://github.com/NREL/pysam/commit/1d3f82e5b6720e5e826dd166172760c0ae39ce4c

I worry about focusing on the dictionary because I am calling it with a dictionary, just one with an invalid structure. It sounds like there are two possible fixes to the error:
(a) Restructure the dictionary
(b) Call assign on a different object

Is there a message that will clue the user in to both of these potential fixes? A verbose idea: "Mismatch between provided input and expected structure. Technology modules often use nested dictionaries. Restructure your input or double check which object to which you are assigning the input."

**Comment by dguittet** [comment]
Great thanks.

I think that sounds good, I'll update it to this:

"Mismatch between provided input and expected structure. PySAM modules are assigned using nested dictionaries. Restructure your input or double check which object to which you are assigning the input."
