### ISSUE TITLE
Issue with assigning inverter parameters for Pvsamv1 model.

### ISSUE THREAD

**Issue by cpd-central** [NREL/pysam#8]
I'm attempting to build a PVsamv1 (Photovoltaic (Detailed)) model and am running into an issue with assigning the temperature derate curve parameter in the InverterDatasheet Group.  I get the same issue in the CEC Inverter Database group.

I am able to assign the Inverter model set to datasheet.  If I then try to assign the datasheet without the 'inv_tdc_ds' parameter set, I get a PySAM.error: "pvsamv1 execution error. precheck input: variable 'inv_tdc_ds' required but not assigned".  Cool, makes sense since this is listed as a required parameter.  I don't have the derate curves in this case so I set to '1' since they are not provided, as per the documentation.  Then, upon running model.execute(), I just get:

"model.InverterDatasheet.assign(inv_datasheet)
PySAM.error"

With no message beyond this.  

Wondering what I'm doing wrong, thanks!

**Comment by dguittet** [comment]
Thanks for the question. `inv_tdc_ds` should be a matrix, the default value is `inv_tdc_ds': ((1.0, 52.8, -0.021),)` which means that when the dc voltage is 1 V, there's an efficiency derate of -0.021 %/C after 52.8 C. If you don't want any derating, you can put ((0, 0, 0)) or something like that. The documentation says it's a sequence[sequence] (ie matrix) so the error you're getting is from assigning a float.

The documentation should not say "set to 1 if not provided", as that's incorrect. I'll have to fix that. Thanks!
