### ISSUE TITLE
How to instanciate the Tcsiscc PySAM module with default parameters?

### ISSUE THREAD

**Issue by JaviBonilla** [NREL/pysam#80]
I am getting an error with this code. I think this used to work in previous versions. Is this no longer valid? Thanks.

```
1   import PySAM.Tcsiscc as Tcsiscc
2 
3   tcsiscc = Tcsiscc.default("ISCCSingleOwner")
```

The error:

```
Traceback (most recent call last):
  File "hybrid_solar_combined_cycle.py", line 3, in <module>
    tcsiscc = Tcsiscc.default("ISCCSingleOwner")
SystemError: <built-in function default> returned a result with an error set
```

**Comment by dguittet** [comment]
The Tcsiscc module is no longer supported after SAM Desktop Version 2018.11.11, so PySAM won't maintain default values either.

If you wanted to use newer PySAM versions while recovering the defaults of this module, you have to download the SAM Desktop, Version 2018.11.11, and export the defaults by calling the "Generate Code" function from a Case with ISCC and then load that from PySAM: https://nrel-pysam.readthedocs.io/en/master/Import.html

**Comment by JaviBonilla** [comment]
Ok, thanks for the info.
