### ISSUE TITLE
PVWattsV7 Broken for 5-min Data

### ISSUE THREAD

**Issue by grantbuster** [NREL/pysam#88]
@dguittet and @janinefreeman, PVWattsV7 won't calculate a mean capacity factor when given an annual 5-minute resource (length of 105120). The profile is still returned. See the attached test file. This fails when using PySAM 2.2.2 but runs successfully with PySAM 2.1.4.

I get this error when trying to retrieve the capacity factor from the outputs attribute:

```
Exception: Runtime error: get_capacity_factor called for SAM_Pvwattsv7 but "capacity_factor" not assigned
```
[test_pysam.zip](https://github.com/NREL/pysam/files/6729281/test_pysam.zip)

**Comment by dguittet** [comment]
Thanks for the example! This is now fixed, and will be added to upcoming release.

**Comment by grantbuster** [comment]
okay great! will this be fixed for all modules? I think i noticed the same behavior in at least one other module (csp maybe?)

**Comment by dguittet** [comment]
The fix here was in the function that calculates whether or not the weather data provided is for an annual simulation and non-annual simulations do not have annual outputs. No other module supports non-annual weather data so this function isn't used in any other module. Do you remember which csp module?

**Comment by grantbuster** [comment]
Sorry, the CSP error is different but similar. I had assumed that it was for all modules. We do have a 5min wind test that is working though.

[test_sam_csp.zip](https://github.com/NREL/pysam/files/6792507/test_sam_csp.zip)

```
Exception: tcsmolten_salt execution error.
compute fail(tcsmolten_salt): The time step duration must be evenly divisible within an hour.
```

**Comment by dguittet** [comment]
Thanks for the example again. I was able to run the module in the test_sam_csp successfully.

**Comment by grantbuster** [comment]
with what pysam version? I got the error in the previous message using 2.2.2. This also doesnt matter so much, we're not running 5min CSP, but it was just an error i had noticed recently.

**Comment by dguittet** [comment]
On the development version I'm working on releasing.

**Comment by grantbuster** [comment]
gotcha, good enough for me, thanks darice!
