### ISSUE TITLE
fopen reaches the maximum 509 limit

### ISSUE THREAD

**Issue by yshime** [NREL/pysam#9]
When using default models, the PySAM_load_defaults function in PySAM_utils.h opens a file and it appears that this file is never closed.

When constructing a model using the .default function such as in PySAM.Pvwattsv5.default('PVWattsNone'), if 509 files have already been open it will return an unable to open file because 509 files are already opened.

I got around this issue by reading the default files once and then copying the parameters into a new model.

Is it necessary that the files be kept open?

**Comment by dguittet** [comment]
Thanks for reporting this bug!

**Comment by dguittet** [comment]
Fixed in #13
