### ISSUE TITLE
Problem with WaveFileReader

### ISSUE THREAD

**Issue by Matthew-Boyd** [NREL/pysam#91]
There's a line continuation problem on line 751 of WaveFileReader.c . I did not fix as I don't know if this file is generated and thus a bigger issue than just adding a '\\'.

![image](https://user-images.githubusercontent.com/30417543/126243064-ccfa9e7f-ef86-4421-88a6-e0e4f891daa0.png)

I added this backslash and it now works fine:
![image](https://user-images.githubusercontent.com/30417543/126243102-09a2d91a-727c-4b50-bdfa-a014478fd8de.png)

**Comment by dguittet** [comment]
@Matthew-Boyd Thanks Matt, I'd noticed this too and it'll be fixed after merging from `dev` branch soon.

**Comment by dguittet** [comment]
fixed
