### ISSUE TITLE
PySAM does not handle 404 responses properly when fetching the weather files

### ISSUE THREAD

**Issue by ghazi-git** [NREL/pysam#94]
This issue happened while using pysam to get the weather file for these coordinates (lng=-76.2002669, lat=43.0402873). The problem is that [the current implementation](https://github.com/NREL/pysam/blob/ef3d8609d7d99a62c550f5835b60aa5133f27461/files/ResourceTools.py#L473) expects the response to be always json when the response.status >= 400. However, a 404 response returns some html instead.

It should be noted that I was **not** able to replicate the error again (running the same code with the above coordinates returns the weather file). Some possible explanations:
- I checked the API calls that happen when getting the weather file. A successful response from `https://gds-hsds-nsrdb-files.nrelcloud.org` usually has the header `x-amz-expiration: expiry-date="Thu, 29 Jul 2021 00:00:00 GMT", rule-id="24 hour retention"` on it. The error I'm reporting happened at `Jul 17, 2021 12:33:53 AM UTC` which seems to be _somewhat close_ to when those files are usually set to expire.
- some temporary issue happened at the time of the request that made the file unavailable.

Even though the issue can't be replicated, I think it's worth it to fix it.

### Additional Info
<details>
<summary>The API call in question that returned a 404 instead of the expected csv file</summary>

```
GET https://gds-hsds-nsrdb-files.nrelcloud.org/data/solar/1171700_43.05_-76.22_tmy-2020_86eaf692167c07fd77a315d87871e274.csv
```
</details>

<details>
<summary>PySAM expected the response to be json while the response was actually some html</summary>

```html
<html>
<head>
  <title>404 Not Found</title>
</head>
<body>
  <h1>404 Not Found</h1>
  <ul>
    <li>Code: NoSuchKey</li>
    <li>Message: The specified key does not exist.</li>
    <li>Key: data/solar/1171700_43.05_-76.22_tmy-2020_86eaf692167c07fd77a315d87871e274.csv</li>
    <li>RequestId: ...</li>
    <li>HostId: ...</li>
  </ul>
  <hr/>
</body>
</html>
```
</details>

<details>
<summary>The relevant part of the traceback</summary>

```
  ...
  File "path/to/helpers.py", line 51, in get_weather_file_from_api
    fetcher = wtkfetcher.fetch(lon_lats)
  File "PySAM/ResourceTools.py", line 577, in fetch
    results.append(self.data_function(job))
  File "PySAM/ResourceTools.py", line 503, in _NSRDB_worker
    data_response_json = data_response.json()
  File "requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```
</details>

<details>
<summary>The code used to get the weather file</summary>

```python
import tempfile

def get_weather_file_from_api(lng, lat) -> str:
    weather_files_tmp_dir = os.path.join(tempfile.gettempdir(), "pysam")
    wtkfetcher = tools.FetchResourceFiles(
        tech="solar",
        nrel_api_key="API_KEY",
        nrel_api_email="EMAIL",
        resource_dir=weather_files_tmp_dir,
    )
    lon_lats = [(lng, lat)]
    fetcher = wtkfetcher.fetch(lon_lats)
    return fetcher.resource_file_paths[0]
```
</details>

**Comment by grgmiller** [comment]
I believe that I am also experiencing the same issue when downloading files from wind toolkit using pysam. When I run my code a second time, the API call works.

I am getting the following error when running `wtkfetcher.fetch(lon_lats)`:

```

~\.conda\envs\switch_247\lib\site-packages\PySAM\ResourceTools.py in fetch(self, points)
--> 545                 results.append(self.data_function(job))

~\.conda\envs\switch_247\lib\site-packages\PySAM\ResourceTools.py in _windtk_worker(self, job)
--> 523                 data_response_json = data_response.json()

~\.conda\envs\switch_247\lib\site-packages\requests\models.py in json(self, **kwargs)
--> 910         return complexjson.loads(self.text, **kwargs)

~\.conda\envs\switch_247\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
--> 357         return _default_decoder.decode(s)

~\.conda\envs\switch_247\lib\json\decoder.py in decode(self, s, _w)
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())

~\.conda\envs\switch_247\lib\json\decoder.py in raw_decode(self, s, idx)
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
